defaults:
  - dataset: mod_subtract_dataset
  - model: grokk_model
  - _self_

dataset:
  frac_train: 0.4
  p: 96

model:
  transformer_config:
    pre_norm: true

train:
  num_workers: 0
  bsize: 512
  lr: 1e-3
  weight_decay: 0.0
  betas: [0.9, 0.98]
  warmup_steps: 10
  eval_every: 10
  eval_batches: 8
  max_steps: 1e6
  preferred_torch_backend: auto

topological_analysis:
  compute_estimates_every: 50
  create_projection_plot_every: 100
  max_number_of_topo_batches: 100
  sampling_seed: 778
  number_of_samples: 1000

wandb:
  use_wandb: true
  wandb_project: grokking_replica

hydra:
  run:
    dir: outputs/run/${hydra.job.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}/
  sweep:
    dir: outputs/multirun/${hydra.job.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}/
    subdir: ${hydra.job.override_dirname}/
  
