defaults:
  - dataset: mod_subtract_dataset
  - logging: default
  - model: grokk_model
  - _self_

dataset:
  frac_train: 0.4
  p: 96
  dataset_seed: 42

model:
  transformer_config:
    pre_norm: true

train:
  num_workers: 0
  bsize: 512
  lr: 1e-3
  weight_decay: 0.0
  betas: [0.9, 0.98]
  warmup_steps: 10
  eval_every: 10
  eval_batches: 8
  max_steps: 1e6
  preferred_torch_backend: auto
  global_seed: 1234
  save_checkpoints_every: 50000
  # Note: Use null to represent None in hydra config (https://stackoverflow.com/questions/76567692/hydra-how-to-express-none-in-config-files)
  load_checkpoint_from_dir: null

topological_analysis:
  compute_estimates_every: 100
  create_projection_plot_every: 10000
  max_number_of_topo_batches: 100
  sampling_seed: 778
  number_of_samples_choices: 
  - 3000
  absolute_n_neighbors_choices:
  - 64
  - 128

wandb:
  use_wandb: true
  wandb_project: grokking_replica
  wandb_dir: wandb/${wandb.wandb_project}/
  wandb_notes: "default notes"

hydra:
  run:
    dir: outputs/run/${hydra.job.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}/
  sweep:
    dir: outputs/multirun/${hydra.job.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}/
    subdir: ${hydra.job.override_dirname}/
  job:
    chdir: False
    config:
      override_dirname:
        exclude_keys:
          - wandb.use_wandb
          - wandb.wandb_project


  
