defaults:
  - dataset: mod_subtract_dataset
  - logging: default
  - model: grokk_model
  - _self_

dataset:
  frac_train: 0.4
  p: 97
  dataset_seed: 42

model:
  transformer_config:
    pre_norm: true

train:
  num_workers: 0
  bsize: 512
  eval_every: 10
  eval_batches: 8
  max_steps: 1e6
  preferred_torch_backend: auto
  global_seed: 1234
  save_checkpoints_every: 50000
  # Note: Use null to represent None in hydra config (https://stackoverflow.com/questions/76567692/hydra-how-to-express-none-in-config-files)
  load_checkpoint_from_dir: null
  lr_scheduler:
    lr_scheduler_type: constant
    warmup_steps: 10
  optimizer:
    lr: 1e-3
    betas: [0.9, 0.98]
    weight_decay: 0.01
    eps: 1e-6
    clip_grad_norm_max_norm: 1.0

topological_analysis:
  compute_estimates_every: 500
  create_projection_plot_every: 20000
  max_number_of_topo_batches: 100
  sampling_seed: 778
  # Note:
  # - We choose 10000 as one of the sample sizes, since for p=96, this will select all operands.
  #   If the value of p is changed, this assumption should be revisited to ensure that
  #   the number of samples is large enough to cover all tokens under consideration.
  number_of_samples_choices: 
  - 3000
  - 10000
  absolute_n_neighbors_choices:
  - 64
  - 128

wandb:
  use_wandb: true
  wandb_project: grokking_replica
  # In the python code, the absolute path to the wandb directory is set to
  # $GROKKING_REPOSITORY_BASE_PATH/wandb_dir
  wandb_dir: wandb/${wandb.wandb_project}/
  wandb_notes: "default notes"
  watch:
    log: "gradients"
    log_freq: 5000

hydra:
  # Notes:
  # - We add the millisecond to the timestamp via '%f' to ensure that the directory is unique
  #   when using multirun on the cluster.
  run:
    dir: outputs/run/${hydra.job.name}/${now:%Y-%m-%d}/${now:%H-%M-%S.%f}/
  sweep:
    dir: outputs/multirun/${hydra.job.name}/${now:%Y-%m-%d}/${now:%H-%M-%S.%f}/
    subdir: ${sanitize_override_dirname:${hydra.job.override_dirname}}/seed=${train.global_seed}/
  job:
    chdir: False
    config:
      override_dirname:
        exclude_keys:
          - train.global_seed
          - wandb.use_wandb
          - wandb.wandb_project


  
